<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SunoRawHarScanner</RootNamespace>
    <AssemblyName>suno-raw-har-scanner</AssemblyName>
    <Product>Suno Raw HAR Scanner</Product>
    <Title>Suno Raw HAR Scanner</Title>
    <Version>1.0.1</Version>
  </PropertyGroup>

</Project>
